dotenv: .env
wallets:
  ACCOUNT1: ${DEAD_ACCOUNT_PUBLIC_KEY_1}
  ACCOUNT2: ${DEAD_ACCOUNT_PUBLIC_KEY_2}
  ACCOUNT3: ${DEAD_ACCOUNT_PUBLIC_KEY_3}
  ACCOUNT4: ${DEAD_ACCOUNT_PUBLIC_KEY_4}
  ACCOUNT5: ${DEAD_ACCOUNT_PUBLIC_KEY_5}
  ACCOUNT6: ${DEAD_ACCOUNT_PUBLIC_KEY_6}
  ACCOUNT7: ${DEAD_ACCOUNT_PUBLIC_KEY_7}
  ACCOUNT8: ${DEAD_ACCOUNT_PUBLIC_KEY_8}
  ACCOUNT9: ${DEAD_ACCOUNT_PUBLIC_KEY_9}
  ACCOUNT10: ${DEAD_ACCOUNT_PUBLIC_KEY_10}
  ACCOUNT11: ${DEAD_ACCOUNT_PUBLIC_KEY_11}
  ACCOUNT12: ${DEAD_ACCOUNT_PUBLIC_KEY_12}
  ACCOUNT13: ${DEAD_ACCOUNT_PUBLIC_KEY_13}
  ACCOUNT14: ${DEAD_ACCOUNT_PUBLIC_KEY_14}
  ACCOUNT15: ${DEAD_ACCOUNT_PUBLIC_KEY_15}
  ACCOUNT16: ${DEAD_ACCOUNT_PUBLIC_KEY_16}
  ACCOUNT17: ${DEAD_ACCOUNT_PUBLIC_KEY_17}
  ACCOUNT18: ${DEAD_ACCOUNT_PUBLIC_KEY_18}
  ACCOUNT19: ${DEAD_ACCOUNT_PUBLIC_KEY_19}
  ACCOUNT20: ${DEAD_ACCOUNT_PUBLIC_KEY_20}